/home/dbensaso/.bashrc: line 12: bind: warning: line editing not enabled
[?1034h/home/dbensaso/.bashrc: line 13: bind: warning: line editing not enabled
/home/dbensaso/.bashrc: line 12: bind: warning: line editing not enabled
/home/dbensaso/.bashrc: line 13: bind: warning: line editing not enabled
/var/spool/slurmd/job3699455/slurm_script: line 12: cd: /home/dbensaso/code/floris/examples/optimization/scipy/Sub_Farms: No such file or directory
/home/dbensaso/code/floris/floris/simulation/wake_velocity/gaussianModels/gauss_legacy.py:182: RuntimeWarning: invalid value encountered in sqrt
  C = 1 - np.sqrt(1 - (Ct * cosd(yaw) / (8.0 * sigma_y * sigma_z / D ** 2)))
Traceback (most recent call last):
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 72, in <module>
    main()
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 60, in main
    run_command_line()
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Galactic_Wind.py", line 206, in <module>
    wind_rose.plot_wind_rose_ti() 
  File "/home/dbensaso/code/floris/floris/tools/wind_rose.py", line 1346, in plot_wind_rose_ti
    df_plot_sub.ti <= ti
  File "/home/dbensaso/.conda-envs/floris/lib/python3.7/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ti'
Plotting the FLORIS flowfield...
Importing wind rose data...
Correcting negative Overhang:-7.5
Correcting negative Overhang:-7.5
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
In: PMI_Abort(1, application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0)
slurmstepd: error: *** STEP 3699455.0 ON r1i1n30 CANCELLED AT 2020-06-30T15:09:28 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: r1i2n4: tasks 72-107: Killed
srun: error: r1i2n27: tasks 144-179: Killed
srun: error: r1i3n30: tasks 288-323: Killed
srun: error: r1i3n0: tasks 180-215: Killed
srun: error: r1i2n2: tasks 36-71: Killed
srun: error: r1i4n24: tasks 324-359: Killed
srun: error: r1i3n28: tasks 252-287: Killed
srun: error: r1i2n5: tasks 108-143: Killed
srun: error: r1i3n4: tasks 216-251: Killed
srun: error: r1i1n30: tasks 0-35: Killed
done?
